ContactCenter/Controllers/YourCustomerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ContactCenter;
using ContactCenter.Common;
using ContactCenter.Models;

namespace ContactCenter.Controllers
{
    public class YourCustomerController : Controller
    {
        private ContactCenterEntities db = new ContactCenterEntities();

        // GET: YourCustomer
        public ActionResult Index()
        {
            int userId = (int)Session["UserID"];
            var cUSTOMERs = db.CUSTOMERs.Include(c => c.USER).Where(w => w.CUSTOMERID != 0 && w.CREATEDBY == userId);
            return View(cUSTOMERs.ToList());
        }

        // GET: YourCustomer/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CUSTOMER cUSTOMER = db.CUSTOMERs.Find(id);
            if (cUSTOMER == null)
            {
                return HttpNotFound();
            }
            else if(cUSTOMER.CREATEDBY != (int)Session["UserID"])
            {
                return RedirectToAction("NotPermitted", "Error");
            }

            return View(cUSTOMER);
        }

        // GET: YourCustomer/Create
        public ActionResult Create()
        {
            ViewBag.CITY = db.CITies.OrderBy(o => o.CITY1).ToList();

            return View();
        }

        // POST: YourCustomer/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CUSTOMER cUSTOMER)
        {
            //ViewBag.CITY = Helpers.GetCityList();
            ViewBag.CITY = db.CITies.OrderBy(o => o.CITY1).ToList();

            ModelState.Remove("CUSTOMERCODE");
            ModelState.Remove("PHONENUMBER");
            ModelState.Remove("EMAIL");
            ModelState.Remove("ADDRESS");
            ModelState.Remove("PLACEOFPRACTICE1");
            ModelState.Remove("STATUS");

            CUSTOMER chkCustomer = db.CUSTOMERs.Where(w => w.CUSTOMERCODE == cUSTOMER.CUSTOMERCODE).FirstOrDefault();

            if (chkCustomer != null)
            {
                ModelState.AddModelError("CUSTOMERCODE", "Customer Code is already exists");
            }
            //if (cUSTOMER.CUSTOMERCODE == null)
            //{
            //    ModelState.AddModelError("CUSTOMERCODE", "Customer Code is required");
            //}
            if (cUSTOMER.FULLNAME == null)
            {
                ModelState.AddModelError("FULLNAME", "Fullname is required");
            }
            if (cUSTOMER.GENDER == null)
            {
                ModelState.AddModelError("GENDER", "Gender is required");
            }
            if (cUSTOMER.CITY == null)
            {
                ModelState.AddModelError("CITY", "City is required");
            }

            if (ModelState.IsValid)
            {
                cUSTOMER.CREATEDDATE = DateTime.Now;
                cUSTOMER.CREATEDBY = Convert.ToInt16(Session["UserID"].ToString());
                cUSTOMER.STATUS = 2;

                try
                {
                    if (cUSTOMER.CUSTOMERCODE == null)
                    {
                        cUSTOMER.CUSTOMERCODE = GenerateCustomerCode();
                    }

                    db.CUSTOMERs.Add(cUSTOMER);
                    db.Configuration.ValidateOnSaveEnabled = false;
                    db.SaveChanges();
                }
                catch (Exception ex)
                {
                    ViewBag.Error = "Create New Customer Failed";
                    LogSystem.ErrorLog(ex, null);
                    //throw;
                    return View(cUSTOMER);
                }

                return RedirectToAction("Index");
            }

            return View(cUSTOMER);
        }

        private string GenerateCustomerCode()
        {
            string newId = "";
            string lastId = db.CUSTOMERs.Where(w => w.CUSTOMERCODE.StartsWith("CS")).Max(m => m.CUSTOMERCODE);
            int number = Convert.ToInt16(lastId.Substring(2, lastId.Length - 2));

            newId = "CS" + (++number).ToString().PadLeft(4, '0');

            return newId;
        }

        // GET: YourCustomer/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CUSTOMER cUSTOMER = db.CUSTOMERs.Find(id);
            if (cUSTOMER == null)
            {
                return HttpNotFound();
            }
            else if (cUSTOMER.CREATEDBY != (int)Session["UserID"])
            {
                return RedirectToAction("NotPermitted", "Error");
            }

            ViewBag.Cities = db.CITies.OrderBy(o => o.CITY1).ToList();

            return View(cUSTOMER);
        }

        // POST: YourCustomer/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CUSTOMER cUSTOMER)
        {
            //ViewBag.Cities = Helpers.GetCityList();
            ViewBag.Cities = db.CITies.OrderBy(o => o.CITY1).ToList();

            ModelState.Remove("CUSTOMERCODE");
            ModelState.Remove("PHONENUMBER");
            ModelState.Remove("EMAIL");
            ModelState.Remove("ADDRESS");
            ModelState.Remove("PLACEOFPRACTICE1");
            ModelState.Remove("STATUS");

            CUSTOMER chkCustomer = db.CUSTOMERs.Where(w => w.CUSTOMERCODE == cUSTOMER.CUSTOMERCODE && w.CUSTOMERID != cUSTOMER.CUSTOMERID).FirstOrDefault();

            if (chkCustomer != null)
            {
                ModelState.AddModelError("CUSTOMERCODE", "Customer Code is already exists");
            }
            if (cUSTOMER.FULLNAME == null)
            {
                ModelState.AddModelError("FULLNAME", "Fullname is required");
            }
            if (cUSTOMER.GENDER == null)
            {
                ModelState.AddModelError("GENDER", "Gender is required");
            }
            if (cUSTOMER.CITY == null)
            {
                ModelState.AddModelError("CITY", "City is required");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var cust = db.CUSTOMERs.AsNoTracking().Where(w => w.CUSTOMERID == cUSTOMER.CUSTOMERID).SingleOrDefault();
                    
                    if(cust.STATUS != 2)
                    {
                        ViewBag.Error = "You cannot Edit this Customer, because it's not in Approval Status";
                        //throw;
                        return View(cUSTOMER);
                    }
                    else
                    {
                        cUSTOMER.STATUS = 2;
                    }

                    db.Entry(cUSTOMER).State = EntityState.Modified;
                    db.Configuration.ValidateOnSaveEnabled = false;
                    db.SaveChanges();
                }
                catch (Exception ex)
                {
                    ViewBag.Error = "Update Customer Failed";
                    LogSystem.ErrorLog(ex, null);
                    //throw;
                    return View(cUSTOMER);
                }

                return RedirectToAction("Index");
            }

            return View(cUSTOMER);
        }

        // GET: YourCustomer/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CUSTOMER cUSTOMER = db.CUSTOMERs.Find(id);
            if (cUSTOMER == null)
            {
                return HttpNotFound();
            }
            return View(cUSTOMER);
        }

        // POST: YourCustomer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CUSTOMER cUSTOMER = db.CUSTOMERs.Find(id);
            db.CUSTOMERs.Remove(cUSTOMER);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ContactCenter/Views/YourCustomer/Delete.cshtml
@model ContactCenter.CUSTOMER

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CUSTOMER</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CUSTOMERCODE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CUSTOMERCODE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FULLNAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FULLNAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GENDER)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GENDER)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PHONENUMBER)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PHONENUMBER)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EMAIL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EMAIL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ADDRESS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ADDRESS)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PLACEOFPRACTICE1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PLACEOFPRACTICE1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PLACEOFPRACTICE2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PLACEOFPRACTICE2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PLACEOFPRACTICE3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PLACEOFPRACTICE3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.STATUS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.STATUS)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CREATEDDATE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CREATEDDATE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SPECIALITY)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SPECIALITY)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CITY1.CITY1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CITY1.CITY1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.USER.USERNAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.USER.USERNAME)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ContactCenter/Views/YourCustomer/Details.cshtml
@using ContactCenter.Common
@model ContactCenter.CUSTOMER

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-content">
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption font-green-sharp">
                        <i class="fa fa-stethoscope font-green-sharp"></i>
                        <span class="caption-subject bold uppercase">Details Your Customer (@Model.CUSTOMERCODE - @Model.FULLNAME)</span>
                        <span class="caption-helper hide"></span>
                    </div>
                </div>
                <div class="portlet-body form">
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.CUSTOMERCODE)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.CUSTOMERCODE)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.FULLNAME)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.FULLNAME)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.GENDER)
                        </dt>

                        <dd>
                            @if (Model.GENDER == 0)
                            {
                                @Html.Raw("Female")
                            }
                            else
                            {
                                @Html.Raw("Male")
                            }
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.PHONENUMBER)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.PHONENUMBER)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.EMAIL)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.EMAIL)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.CITY)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.CITY1.CITY1)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.ADDRESS)
                        </dt>

                        <dd>
                            @*@Html.DisplayFor(model => model.ADDRESS)*@
                            @if (!string.IsNullOrEmpty(Model.ADDRESS))
                            {
                                @Html.Raw(Model.ADDRESS.Replace("\r\n", "<br>").Replace("\n", "<br>"))
                            }
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.PLACEOFPRACTICE1)
                        </dt>

                        <dd>
                            @*@Html.DisplayFor(model => model.PLACEOFPRACTICE1)*@
                            @if (!string.IsNullOrEmpty(Model.PLACEOFPRACTICE1))
                            {
                                @Html.Raw(Model.PLACEOFPRACTICE1.Replace("\r\n", "<br>").Replace("\n", "<br>"))
                            }
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.PLACEOFPRACTICE2)
                        </dt>

                        <dd>
                            @*@Html.DisplayFor(model => model.PLACEOFPRACTICE2)*@
                            @if (!string.IsNullOrEmpty(Model.PLACEOFPRACTICE2))
                            {
                                @Html.Raw(Model.PLACEOFPRACTICE2.Replace("\r\n", "<br>").Replace("\n", "<br>"))
                            }
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.PLACEOFPRACTICE3)
                        </dt>

                        <dd>
                            @*@Html.DisplayFor(model => model.PLACEOFPRACTICE3)*@
                            @if (!string.IsNullOrEmpty(Model.PLACEOFPRACTICE3))
                            {
                                @Html.Raw(Model.PLACEOFPRACTICE3.Replace("\r\n", "<br>").Replace("\n", "<br>"))
                            }
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.STATUS)
                        </dt>

                        <dd>
                            @if (Model.STATUS == 0)
                            {
                                <span class="label label-danger"> Inactive </span>
                            }
                            else
                            {
                                <span class="label label-success"> Active </span>
                            }
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.CREATEDDATE)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.CREATEDDATE)
                        </dd>

                        <dt>
                            Created By
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.USER.USERNAME)
                        </dd>

                    </dl>

                    <div class="form-actions no-color">
                        @*<input type="submit" value="Delete" class="btn btn-default" /> |
                            @Html.ActionLink("Back to List", "Index")*@
                        <div class="col-md-offset-2 col-md-10">
                            @if (Model.STATUS == (int)Status.Approval)
                            {
                                <a href="@Url.Action("Edit", "YourCustomer", new { id = Model.CUSTOMERID })" class="btn btn-success" id="btn-save">
                                    <i class="fa fa-pencil"></i>
                                    Edit
                                </a>
                            }
                            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn default" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ContactCenter/Views/YourCustomer/Index.cshtml
@using ContactCenter.Common
@model IEnumerable<ContactCenter.CUSTOMER>

@{
    ViewBag.Title = "Your Customer List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-content">
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption font-green-sharp">
                        <i class="fa fa-stethoscope font-green-sharp"></i>
                        <span class="caption-subject bold uppercase">Your Customer List</span>
                        <span class="caption-helper hide"></span>
                    </div>
                </div>
                <div class="portlet-body">
                    <div id="dv-alert"></div>
                    <div class="table-toolbar">
                        <div class="row">
                            <div class="col-md-6">
                                <a class="btn sbold green" id="btn-add" href="@Url.Action("Create", "YourCustomer")">
                                    <i class="fa fa-plus"></i>
                                    Add New Customer
                                </a>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-12">
                                @if (ViewBag.Error != null && ViewBag.Error != "")
                                {
                                    <div class='alert alert-danger text-center mrg0B mrg15T' role='alert'>
                                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
                                        <b>@ViewBag.Error</b>
                                    </div>
                                }

                                @if (ViewBag.Success != null && ViewBag.Success != "")
                                {
                                    <div class='alert alert-success text-center mrg0B mrg15T' role='alert'>
                                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
                                        <b>@ViewBag.Success</b>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>

                    <table class="table table-striped table-bordered table-hover dataTable" id="user-list">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.CUSTOMERCODE)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.FULLNAME)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.PHONENUMBER)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.CITY)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.STATUS)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.CREATEDDATE)
                                </th>
                                <th>
                                    Created By
                                </th>
                                <th style="min-width: 100px"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CUSTOMERCODE)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.FULLNAME)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.PHONENUMBER)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CITY1.CITY1)
                                    </td>
                                    <td>
                                        @*@Html.DisplayFor(modelItem => item.STATUS)*@

                                        @switch (item.STATUS)
                                        {
                                            case 0:
                                                <span class="label label-danger"> Inactive </span>
                                                break;
                                            case 1:
                                                <span class="label label-success"> Active </span>
                                                break;
                                            case 2:
                                                <span class="label label-warning"> Approval </span>
                                                break;

                                        }
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CREATEDDATE)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.USER.USERNAME)
                                    </td>
                                    <td class="text-center">
                                        <a href="@Url.Action("Details", "YourCustomer", new { id = item.CUSTOMERID })" title="Details" class="btn yellow btn-xs btn-eye">
                                            <i class="fa fa-eye"></i>
                                        </a>

                                        @if (item.STATUS == (int)Status.Approval)
                                        {
                                            <a href="@Url.Action("Edit", "YourCustomer", new { id = item.CUSTOMERID })" title="Edit" class="btn green btn-xs btn-edit">
                                                <i class="fa fa-pencil"></i>
                                            </a>
                                        }

                                        @*<a href="@Url.Action("Delete", "Customer", new { id = item.CUSTOMERID })" title="Delete" class="btn red btn-xs btn-disable">
                                                <i class="fa fa-remove"></i>
                                            </a>*@
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>