ContactCenter/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ContactCenter;
using ContactCenter.Common;
using ContactCenter.Models;
using System.Threading.Tasks;
using ContractCenter.Common;
using System.Net.Mail;
using System.Web.UI.WebControls;
using System.IO;
using System.Web.UI;
using System.Linq.Dynamic;
using System.Configuration;

namespace ContactCenter.Controllers
{
    public class OrderController : Controller
    {
        private ContactCenterEntities db = new ContactCenterEntities();

        // GET: Order
        public ActionResult Index()
        {
            ViewBag.Cities = db.CITies.OrderBy(o => o.CITY1).ToList();
            ViewBag.List = null;
            //var oRDERDETAILs = db.ORDERDETAILs.Include(i => i.ORDER.CUSTOMER).Include(i => i.ORDER.PHARMACY).Include(i => i.PRODUCT);

            var OrderList = (from o in db.ORDERs
                            join od in db.ORDERDETAILs
                            on o.ORDERID equals od.ORDERID into JoinedEmpDept
                            from od in JoinedEmpDept.DefaultIfEmpty()
                            select new OrderIndexViewModel
                            {
                                ORDER = o,
                                ORDERDETAIL = od
                            }).ToList();

            if((UserRole)Session["UserRole"] == UserRole.ContactCenter)
            {
                int iUserID = Convert.ToInt32(Session["UserID"].ToString());
                OrderList = OrderList.Where(w => w.ORDER.CREATEDBY == iUserID).ToList();
            }

            return View(OrderList.ToList());
        }

        public async Task<ActionResult> TestEmail(int? id)
        {
            ORDER o = db.ORDERs.Find(id);

            await SendNotifyEmail((int)OrderStatus.Complete, o);

            return RedirectToAction("Index");
        }

        public ActionResult CompleteList()
        {
            ViewBag.Cities = db.CITies.OrderBy(o => o.CITY1).ToList();
            ViewBag.List = (int)OrderStatus.Confirmed;
            //var oRDERDETAILs = db.ORDERDETAILs.Include(i => i.ORDER.CUSTOMER).Include(i => i.ORDER.PHARMACY).Include(i => i.PRODUCT).Where(w => w.ORDER.STATUS == (int)OrderStatus.Submitted);

            var OrderList = (from o in db.ORDERs
                            join od in db.ORDERDETAILs
                            on o.ORDERID equals od.ORDERID into JoinedEmpDept
                            from od in JoinedEmpDept.DefaultIfEmpty()
                            where o.STATUS == (int)OrderStatus.Confirmed
                            select new OrderIndexViewModel
                            {
                                ORDER = o,
                                ORDERDETAIL = od
                            }).ToList();
            
            if ((UserRole)Session["UserRole"] == UserRole.ContactCenter)
            {
                int iUserID = Convert.ToInt32(Session["UserID"].ToString());
                OrderList = OrderList.Where(w => w.ORDER.CREATEDBY == iUserID).ToList();
            }

            return View(OrderList.ToList());
        }

        public async Task<ActionResult> Complete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ORDER oRDER = new ORDER();

            oRDER = db.ORDERs.Find(id);
            oRDER.STATUS = (int)OrderStatus.Complete;

            try
            {
                db.Entry(oRDER).State = EntityState.Modified;
                db.SaveChanges();

                await SendNotifyEmail((int)OrderStatus.Complete, oRDER);
            }
            catch (Exception ex)
            {
                LogSystem.ErrorLog(ex, null);
                return RedirectToAction("CompleteList");
            }

            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Confirm(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ORDER oRDER = new ORDER();

            oRDER = db.ORDERs.Find(id);
            oRDER.STATUS = (int)OrderStatus.Confirmed;

            try
            {
                db.Entry(oRDER).State = EntityState.Modified;
                db.SaveChanges();

                await SendNotifyEmail((int)OrderStatus.Confirmed, oRDER);
            }
            catch (Exception ex)
            {
                LogSystem.ErrorLog(ex, null);
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Reject(int? ORDERID, string REASON, string ddlReason)
        {
            if (ORDERID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            string s_reason = ddlReason == "" ? REASON : ddlReason;
            ORDER oRDER = new ORDER();

            oRDER = db.ORDERs.Find(ORDERID);
            oRDER.REJECTREASON = s_reason;
            oRDER.STATUS = (int)OrderStatus.Rejected;

            try
            {
                db.Entry(oRDER).State = EntityState.Modified;
                db.SaveChanges();

                await SendNotifyEmail((int)OrderStatus.Rejected, oRDER);
            }
            catch (Exception ex)
            {
                LogSystem.ErrorLog(ex, null);
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

        // GET: Order/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderViewModel OVM = new OrderViewModel();

            OVM.ORDER = db.ORDERs.Find(id);
            OVM.ORDERDETAILList = OVM.ORDER.ORDERDETAILs.ToList();

            if (OVM.ORDER == null)
            {
                return HttpNotFound();
            }

            return View(OVM);
        }

        [HttpGet]
        public ActionResult Reorder(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            OrderViewModel OVM = new OrderViewModel();
            OVM = GenerateOrderDDL(OVM);

            OVM.Title = "Reorder";
            OVM.ORDER = db.ORDERs.Include(i => i.ORDERDETAILs).Include(i => i.CUSTOMER).Include(i => i.PHARMACY).SingleOrDefault(s => s.ORDERID == id);
            OVM.ORDER.ORDERID = 0;
            OVM.ORDER.STATUS = null;
            OVM.ORDERDETAILList = OVM.ORDER.ORDERDETAILs.ToList();

            return View("Create", OVM);
        }

        // GET: Order/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            OrderViewModel OVM = new OrderViewModel();
            OVM = GenerateOrderDDL(OVM);
            OVM.Title = "Edit Order";

            if (OVM == null)
            {
                return HttpNotFound();
            }

            OVM.ORDER = db.ORDERs.Include(i => i.ORDERDETAILs).Include(i => i.CUSTOMER).Include(i => i.PHARMACY).SingleOrDefault(s => s.ORDERID == id);
            OVM.ORDERDETAILList = OVM.ORDER.ORDERDETAILs.ToList();
            
            //SOURCE ORDER
            List<DropdownLIST> SL = GenerateSourceOrder();
            ViewBag.SourceOrderList = new SelectList(SL, "Value", "Text");

            //INFO DISCOUNT CUS
            List<DropdownLIST> IDCL = GenerateInfoDiscoutCust();
            ViewBag.IDCList = new SelectList(IDCL, "Value", "Text");

            //SUBMISSION OF DISCOUNTS
            List<DropdownLIST> SOD = GenerateSubmissionOfDiscount();
            ViewBag.SODList = new SelectList(SOD, "Value", "Text");

            return View("Create", OVM);
        }

        public async Task SendNotifyEmail(int oStatus, ORDER o)
        {
            string subject = "[PURCHASE ORDER #" + o.ORDERID + "] - " + Helpers.AppName;
            string ccEmail = ConfigurationManager.AppSettings["CallCenterEmail"].ToString();
            string sanofiEmail = ConfigurationManager.AppSettings["SanofiEmail"].ToString();

            if (o.CUSTOMERID == 0)
            {
                o.CUSTOMER = db.CUSTOMERs.Find(0);
            }

            string bodyCustomer = MailTemplate.ConstructOrderNotification(new EmailRecipient { Name = o.CUSTOMER.FULLNAME, ORDER = o, ORDERDETAILList = o.ORDERDETAILs.ToList(), RecipientType = RecipientType.Customer });
            string bodyDistributor = MailTemplate.ConstructOrderNotification(new EmailRecipient { Name = o.DISTRIBUTORNAME, ORDER = o, ORDERDETAILList = o.ORDERDETAILs.ToList(), RecipientType = RecipientType.Distributor });
            string bodyPharmacy = MailTemplate.ConstructOrderNotification(new EmailRecipient { Name = o.PHARMACY.PHARMACYNAME, ORDER = o, ORDERDETAILList = o.ORDERDETAILs.ToList(), RecipientType = RecipientType.Pharmacy });

            List<string> bcc = new List<string>(new string[] { sanofiEmail });

            if (oStatus == (int)OrderStatus.Submitted)
            {
                List<string> to = new List<string>(new string[] { o.DISTRIBUTOREMAIL, ccEmail });

                // TODO: if use toList, please add Helpers.AppName for from recipient displayName
                MailMessage mailDistributor = Mailer.ConstructMailMessage(to, null, bcc, subject, bodyDistributor, true, Helpers.AppName);

                await Task.WhenAll(
                    Mailer.SmtpSendAsync(mailDistributor)
                );
            }

ContactCenter/Controllers/UserManagementController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ContactCenter;
using ContactCenter.Common;
using System.Data.Entity.Validation;
using Cryptography;

namespace ContactCenter.Controllers
{
    public class UserManagementController : Controller
    {
        private ContactCenterEntities db = new ContactCenterEntities();
        private AES_Cryptography crypto = new AES_Cryptography();

        // GET: UserManagement
        public ActionResult Index()
        {
            var uSERs = db.USERs.Include(u => u.USER2);
            return View(uSERs.ToList());
        }

        // GET: UserManagement/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            USER uSER = db.USERs.Find(id);
            if (uSER == null)
            {
                return HttpNotFound();
            }
            return View(uSER);
        }

        // GET: UserManagement/Create
        public ActionResult Create()
        {
            GenerateDDL();

            return View();
        }

        // POST: UserManagement/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(USER uSER)
        {
            USER chkUser = db.USERs.Where(w => w.USERNAME == uSER.USERNAME).FirstOrDefault();
            GenerateDDL();

            if (chkUser != null)
            {
                ModelState.AddModelError("USERNAME", "Username is already exists");
            }

            if (ModelState.IsValid)
            {
                uSER.PASSWORD = crypto.encryptString(UserHelper.DefaultPassword);
                uSER.CREATEDBY = Convert.ToInt16(Session["UserID"].ToString());
                uSER.CREATEDDATE = DateTime.Now;
                try
                {
                    db.USERs.Add(uSER);
                    db.SaveChanges();
                }
                catch (Exception ex)
                {
                    ViewBag.Error = "Create New User Failed";
                    LogSystem.ErrorLog(ex, null);
                    //throw;
                    return View(uSER);
                }

                return RedirectToAction("Index");
            }
            
            return View(uSER);
        }

        // GET: UserManagement/Edit/5
        public ActionResult Edit(int? id)
        {
            GenerateDDL();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            USER uSER = db.USERs.Find(id);
            if (uSER == null)
            {
                return HttpNotFound();
            }

            return View(uSER);
        }

        // POST: UserManagement/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(USER uSER, bool IsReset)
        {
            GenerateDDL();

            if (ModelState.IsValid)
            {
                if (IsReset)
                    uSER.PASSWORD = crypto.encryptString(UserHelper.DefaultPassword);
                
                try
                {
                  
                    db.Entry(uSER).State = EntityState.Modified;
                    db.SaveChanges();
                }
                catch (Exception ex)
                {
                    ViewBag.Error = "Update User Failed";
                    LogSystem.ErrorLog(ex, null);
                    //throw;
                    return View(uSER);
                }

                return RedirectToAction("Index");
            }
            
            return View(uSER);
        }

        // GET: UserManagement/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    USER uSER = db.USERs.Find(id);
        //    if (uSER == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(uSER);
        //}

        // POST: UserManagement/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            USER uSER = db.USERs.Find(id);
            db.USERs.Remove(uSER);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        private void GenerateDDL()
        {
            ViewBag.Roles = EnumHelper.ToOrderedSelectList<UserRole>();
            ViewBag.Statuses = EnumHelper.ToOrderedSelectList<Status>();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ContactCenter/Views/Shared/_SideMenu.cshtml
@using ContactCenter.Common

<div class="page-sidebar-wrapper">
    <div class="page-sidebar navbar-collapse collapse">
        @{var role = (UserRole)Session["UserRole"];}

        <ul class="page-sidebar-menu   " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
            @if (role == UserRole.Admin)
            {
                <li class="heading">
                    <h3 class="uppercase">MANAGEMENT</h3>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Index", "UserManagement")" class="nav-link nav-toggle">
                    <i class="icon-users"></i>
                    <span class="title">User Management</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Index", "Product")" class="nav-link nav-toggle">
                        <i class="icon-social-dropbox"></i>
                        <span class="title">Product Management</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Index", "Customer")" class="nav-link nav-toggle">
                        <i class="fa fa-side-menu fa-stethoscope"></i>
                        <span class="title">Customer Management</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Approval", "Customer")" class="nav-link nav-toggle">
                        <i class="fa fa-side-menu fa-check"></i>
                        <span class="title">Customer Approval</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Index", "Channel")" class="nav-link nav-toggle">
                        <i class="fa fa-side-menu fa-medkit"></i>
                        <span class="title">Channel Management</span>
                    </a>
                </li>
            }
            <li class="heading">
                <h3 class="uppercase">transaction</h3>
            </li>
            <li class="nav-item">
                <a href="@Url.Action("Create", "Order")" class="nav-link nav-toggle">
                    <i class="fa fa-side-menu fa-paper-plane-o"></i>
                    <span class="title">New Order</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="@Url.Action("Index", "Order")" class="nav-link nav-toggle">
                    <i class="icon-basket "></i>
                    <span class="title">Order Management</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="@Url.Action("CompleteList", "Order")" class="nav-link nav-toggle">
                    <i class="icon-check "></i>
                    <span class="title">Complete Order</span>
                </a>
            </li>
            @if ((UserRole)Session["UserRole"] == UserRole.ContactCenter)
            {
                <li class="heading">
                    <h3 class="uppercase">your customer</h3>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Create", "YourCustomer")" class="nav-link nav-toggle">
                        <i class="fa fa-side-menu fa-plus"></i>
                        <span class="title">Add New Customer</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Index", "YourCustomer")" class="nav-link nav-toggle">
                        <i class="fa fa-side-menu fa-stethoscope"></i>
                        <span class="title">Your Customer List</span>
                    </a>
                </li>
            }
        </ul>
    </div>
</div>