ContactCenter/Controllers/ChannelController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ContactCenter.Common;
using System.IO;
using System.Data.OleDb;
using System.Text.RegularExpressions;
using ContactCenter.Models;
using System.Web.UI.WebControls;
using System.Web.UI;
using System.Linq.Dynamic;
namespace ContactCenter.Controllers
{
    public class ChannelController : Controller
    {
        private ContactCenterEntities db = new ContactCenterEntities();

        // GET: Pharmacy
        public ActionResult Index()
        {
            var pHARMACies = db.PHARMACies.Include(p => p.USER);
            return View(pHARMACies.ToList());
        }

        public ActionResult Download()
        {
            string filename = "Upload Channel Template.xlsx";
            string file = Server.MapPath("~/Content/Templates/" + filename);
            string contentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            return File(file, contentType, Path.GetFileName(file));
        }

        [HttpGet]
        public ActionResult Import()
        {
            var pHARMACies = db.PHARMACies.Include(p => p.USER);
            return View("Index", pHARMACies.ToList());
        }

        [HttpPost]
        public ActionResult Import(HttpPostedFileBase excelfile)
        {
            //LogSystem logging = new LogSystem();
            try
            {
                if (excelfile == null || excelfile.ContentLength == 0)
                {
                    ViewBag.Error = "Please select an Excel File";

                    var pHARMACies = db.PHARMACies.Include(p => p.USER);
                    return View("Index", pHARMACies.ToList());
                }
                else
                {
                    if (excelfile.FileName.EndsWith("xls") || excelfile.FileName.EndsWith("xlsx") || excelfile.FileName.EndsWith("xlsb"))
                    {
                        //string consString = ConfigurationManager.ConnectionStrings["SQLConnect1"].ConnectionString;
                        //SQLConnect connSQL = new SQLConnect(consString);

                        string fileName = "";
                        if (excelfile.FileName.Contains('/'))
                        {
                            string[] aa = excelfile.FileName.Split('/');
                            fileName = aa[aa.Length - 1];
                        }
                        else
                        {
                            if (excelfile.FileName.Contains('\\'))
                            {
                                string[] aa = excelfile.FileName.Split('\\');
                                fileName = aa[aa.Length - 1];
                            }
                            else
                            {
                                fileName = excelfile.FileName;
                            }
                        }
                        string extension = System.IO.Path.GetExtension(excelfile.FileName);
                        string path1 = string.Format("{0}/{1}", Server.MapPath("~/Content/UploadedFolder"), fileName);

                        if (System.IO.File.Exists(path1))
                            System.IO.File.Delete(path1);

                        excelfile.SaveAs(path1);

                        string excelConnectionString = string.Empty;

                        excelConnectionString = @"Provider=Microsoft.ACE.OLEDB.12.0;Data Source=" + path1 + ";Extended Properties=Excel 12.0;Persist Security Info=False";
                        //excelConnectionString = @"Provider=Microsoft.Jet.OLEDB.4.0;Data Source = '" + path1 + "';Extended Properties=\"Excel 8.0;HDR=YES;\"";
                   

                        //OleDbConnection conn = new OleDbConnection(excelConnectionString);

                        using (OleDbConnection conn = new OleDbConnection(excelConnectionString))
                        {
                            try
                            {
                                if (conn.State == ConnectionState.Closed)
                                    conn.Open();

                                DataTable dtExcelSchema;
                                dtExcelSchema = conn.GetOleDbSchemaTable(OleDbSchemaGuid.Tables, null);

                                string sheetName = "Sheet1";
                                string query = "SELECT * FROM [" + sheetName + "$]";

                                OleDbCommand cmd = new OleDbCommand(query, conn);
                                OleDbDataAdapter da = new OleDbDataAdapter(cmd);
                                DataSet ds = new DataSet();

                                da.Fill(ds);
                                DateTime today = DateTime.Now;

                                // validate upload
                                if (!Validate(ds.Tables[0]))
                                {
                                    ViewBag.Error = "See error message below";

                                    var pHARMACies = db.PHARMACies.Include(p => p.USER);
                                    return View("Index", pHARMACies.ToList());
                                }

                                int val = 0;

                                using (var dbTran = db.Database.BeginTransaction())
                                {
                                    var pHARMACies = db.PHARMACies.Include(p => p.USER);

                                    try
                                    {
                                        foreach (DataRow dr in ds.Tables[0].Rows)
                                        {
                                            string channel_code   = dr["CHANNEL_CODE"].ToString().Trim().TrimStart().TrimEnd();
                                            string channel_name   = dr["CHANNEL_NAME"].ToString().Trim().TrimStart().TrimEnd();
                                            string phone_number   = dr["PHONE_NUMBER"].ToString().Trim().TrimStart().TrimEnd();
                                            string phone_number2  = dr["PHONE_NUMBER2"].ToString().Trim().TrimStart().TrimEnd();
                                            string email          = dr["EMAIL"].ToString().Trim().TrimStart().TrimEnd();
                                            string city           = dr["CITY"].ToString().Trim().TrimStart().TrimEnd();
                                            string address        = dr["ADDRESS"].ToString().Trim().TrimStart().TrimEnd();
                                            string type           = dr["TYPE"].ToString().Trim().TrimStart().TrimEnd();
                                            string plant          = dr["PLANT"].ToString().Trim().TrimStart().TrimEnd();
                                            // TODO: panel not used yet
                                            string panel          = dr["PANEL"].ToString().Trim().TrimStart().TrimEnd();

                                            int i_city = db.CITies.Where(w => w.CITY1 == city).Select(s => s.ID).SingleOrDefault();

                                            PHARMACY c = new PHARMACY();
                                            c.PHARMACYCODE  = channel_code;
                                            c.PHARMACYNAME  = channel_name;
                                            c.PHONENUMBER   = phone_number;
                                            c.PHONENUMBER2 = phone_number2;
                                            c.EMAIL         = email;
                                            c.CITY          = i_city;
                                            c.ADDRESS       = address;
                                            c.TYPE          = char.ToUpper(type[0]) + type.ToLower().Substring(1);
                                            c.PHARMACYPLANT = plant;
                                            // TODO: panel not used yet
                                            //c.PANEL = panel == "Y" ? 1 : 0;

                                            c.STATUS = (int)Status.Active;
                                            c.CREATEDBY = Convert.ToInt16(Session["UserID"].ToString());
                                            c.CREATEDDATE = DateTime.Now;
                                            db.PHARMACies.Add(c);
                                        }
                                        db.SaveChanges();

                                        dbTran.Commit();
                                    }
                                    catch (Exception ex)
                                    {
                                        dbTran.Rollback();
                                        LogSystem.ErrorLog(ex, null);
                                        ViewBag.Error = "Data failed to insert";

                                        return View("Index", pHARMACies.ToList());
                                    }

                                    ViewBag.Success = "Import Channel Success";
                                    return View("Index", pHARMACies.ToList());
                                }
                            }
                            catch (Exception exx)
                            {
                                conn.Close();
                                throw;
                            }
                        }
                    }
                    else
                    {
                        ViewBag.Error = "File type is incorrect";
                        
                        var pHARMACies = db.PHARMACies.Include(p => p.USER);
                        return View("Index", pHARMACies.ToList());
                    }

                }
            }
            catch (Exception ex)
            {
                //logging.ErrorLog(ex, null);
                LogSystem.ErrorLog(ex, null);

ContactCenter/Views/Channel/Details.cshtml
@model ContactCenter.PHARMACY

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-content">
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption font-green-sharp">
                        <i class="fa fa-medkit font-green-sharp"></i>
                        <span class="caption-subject bold uppercase">Details Channel (@Model.PHARMACYCODE - @Model.PHARMACYNAME)</span>
                        <span class="caption-helper hide"></span>
                    </div>
                </div>
                <div class="portlet-body form">
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.PHARMACYCODE)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.PHARMACYCODE)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.PHARMACYNAME)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.PHARMACYNAME)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.TYPE)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.TYPE)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.PHONENUMBER)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.PHONENUMBER)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.PHONENUMBER2)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.PHONENUMBER2)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.EMAIL)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.EMAIL)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.CITY)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.CITY1.CITY1)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.ADDRESS)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.ADDRESS)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.PHARMACYPLANT)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.PHARMACYPLANT)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.STATUS)
                        </dt>

                        <dd>
                            @if (Model.STATUS == 0)
                            {
                                <span class="label label-danger"> Inactive </span>
                            }
                            else
                            {
                                <span class="label label-success"> Active </span>
                            }
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.CREATEDDATE)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.CREATEDDATE)
                        </dd>

                        <dt>
                            Created By
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.USER.USERNAME)
                        </dd>

                    </dl>
                    <div class="form-actions no-color">
                        @*<input type="submit" value="Delete" class="btn btn-default" /> |
                            @Html.ActionLink("Back to List", "Index")*@
                        <div class="col-md-offset-2 col-md-10">
                            @*<input type="submit" value="Create" class="btn btn-default" />*@
                            <a href="@Url.Action("Edit", "Channel", new { id = Model.PHARMACYID })" class="btn btn-success" id="btn-save">
                                <i class="fa fa-pencil"></i>
                                Edit
                            </a>
                            @*<a href="@Url.Action("Delete", "Pharmacy", new { id = Model.PHARMACYID })" class="btn btn-danger" id="btn-save">
                                <i class="fa fa-trash-o"></i>
                                Delete
                            </a>*@
                            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn default" })
                        </div>
                    </div>
                </div>

                @*<p>
                        @Html.ActionLink("Edit", "Edit", new { id = Model.CUSTOMERID }) |
                        @Html.ActionLink("Back to List", "Index")
                    </p>*@
            </div>
        </div>
    </div>
</div>

ContactCenter/Views/Channel/Index.cshtml
@model IEnumerable<ContactCenter.PHARMACY>

@{
    ViewBag.Title = "Channel List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-content">
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption font-green-sharp">
                        <i class="fa fa-medkit font-green-sharp"></i>
                        <span class="caption-subject bold uppercase">Channel List</span>
                        <span class="caption-helper hide"></span>
                    </div>
                </div>
                <div class="portlet-body">
                    <div id="dv-alert"></div>
                    <div class="table-toolbar">
                        <div class="row">
                            <div class="col-md-12">
                                <a class="btn sbold green" id="btn-add" href="@Url.Action("Create", "Channel")">
                                    <i class="fa fa-plus"></i>
                                    Add New Channel
                                </a>
                                <a class="btn sbold blue pull-right" target="_blank" href="@Url.Action("Export", "Channel")">
                                    <i class="fa fa-download"></i>
                                    Export to Excel
                                </a>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-12">
                                @if (ViewBag.Error != null && ViewBag.Error != "")
                                {
                                    <div class='alert alert-danger text-center mrg0B mrg15T' role='alert'>
                                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
                                        <b>@ViewBag.Error</b>
                                    </div>
                                }

                                @if (ViewBag.Success != null && ViewBag.Success != "")
                                {
                                    <div class='alert alert-success text-center mrg0B mrg15T' role='alert'>
                                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
                                        <b>@ViewBag.Success</b>
                                    </div>
                                }
                            </div>
                        </div>
                                                
                        <div class="row">
                            <div class="col-md-12">
                                <div class="portlet box blue mrg0B mrg15T">
                                    <div class="portlet-title">
                                        <div class="caption">
                                            <i class="icon-cloud-upload"></i>Upload Channel
                                        </div>
                                    </div>
                                    <div class="portlet-body pad15A">
                                        @using (Html.BeginForm("Import", "Channel", FormMethod.Post, new { enctype = "multipart/form-data" }))
                                        {
                                            <table>
                                                <tr>
                                                    <td width="300px">
                                                        <div class="input-group">
                                                            <input type="text" class="form-control" placeholder="filename.." readonly>
                                                            <span class="input-group-btn">
                                                                <span class="btn btn-sample btn-file">
                                                                    <i class="icon-magnifier "></i> Browse <input type="file" name="excelfile" />
                                                                </span>
                                                            </span>
                                                        </div>
                                                    </td>
                                                    <td style="padding-left:10px">
                                                        @*<input type="submit" class="btn btn-success" name="submitimport" value="Upload" />*@
                                                        <button type="submit" class="btn btn-success" id="btn-save">
                                                            <i class="icon-cloud-upload "></i>
                                                            Upload
                                                        </button>
                                                    </td>
                                                    <td style="padding-left:10px">
                                                        @Html.ActionLink("Download Template", "Download", "Channel", null, new { @class = "btn btn-default" })
                                                    </td>
                                                </tr>
                                                @if (ViewBag.error != null)
                                                {
                                                    <tr>
                                                        <td colspan="3" class="text-danger">
                                                            <br />
                                                            @Html.Raw(ViewBag.error)
                                                        </td>
                                                    </tr>
                                                }
                                            </table>

                                            // validate upload
                                            if (ViewBag.ErrorUpload != null)
                                            {
                                                <br />
                                                <table class="table display table-bordered table-hover table-striped">
                                                    <thead>
                                                        <tr class="danger text-danger">
                                                            <th class="text-center" width="15%">Row Number</th>
                                                            <th class="text-center">Error Message</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        @{string[,] msgs = ViewBag.ErrorUpload as string[,];}
                                                        @for (int i = 0; i <= msgs.GetUpperBound(0); i++)
                                                        {
                                                            if (msgs[i, 0] != "" && msgs[i, 0] != null)
                                                            {
                                                                <tr>
                                                                    <td class="text-center">@msgs[i, 0]</td>
                                                                    <td class="text-danger">@Html.Raw(@msgs[i, 1])</td>
                                                                </tr>
                                                            }
                                                        }
                                                    </tbody>
                                                </table>
                                            }
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <table class="table table-striped table-bordered table-hover dataTable" id="user-list">
                        <thead>
                            <tr>
                                <th>
                                    Channel Code
                                </th>
                                <th>
                                    Channel Name
                                </th>
                                <th>
                                    Channel Type
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.PHONENUMBER)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.CITY)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.STATUS)
                                </th>
                                @*<th>
                                    @Html.DisplayNameFor(model => model.CREATEDDATE)
                                </th>*@
                                <th style="min-width: 100px"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.PHARMACYCODE)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.PHARMACYNAME)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.TYPE)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.PHONENUMBER)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CITY1.CITY1)
                                    </td>
                                    <td>
                                        @if (item.STATUS > 0)
                                        {
                                            <span class="label label-success"> Active </span>
                                        }
                                        else
                                        {
                                            <span class="label label-danger"> Inactive </span>
                                        }
                                    </td>
                                    @*<td>
                                        @Html.DisplayFor(modelItem => item.CREATEDDATE)
                                    </td>*@
                                    <td class="text-center">
                                        <a href="@Url.Action("Details", "Channel", new { id = item.PHARMACYID })" title="Details" class="btn yellow btn-xs btn-eye">
                                            <i class="fa fa-eye"></i>
                                        </a>

                                        <a href="@Url.Action("Edit", "Channel", new { id = item.PHARMACYID })" title="Edit" class="btn green btn-xs btn-edit">
                                            <i class="fa fa-pencil"></i>
                                        </a>

                                        @*<a href="@Url.Action("Delete", "Pharmacy", new { id = item.PHARMACYID })" title="Delete" class="btn red btn-xs btn-disable">
                                            <i class="fa fa-remove"></i>
                                        </a>*@
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>